services:
  mysql:
    image: mysql:8.0
    container_name: mysql8_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-appdb}
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "${HOST_MYSQL_PORT:-3307}:3306"   # host:container  <-- LIST item (note the dash)
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
